name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
permissions:
  contents: write

jobs:
  github-pages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: src